version: '3.8'

services:
  db:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_API_BASE_URL: https://api.openai.com/v1
      OPENAI_API_MODEL: gpt-3.5-turbo
      DATABASE_URL: postgres://user:password@db:5432/db
    ports:
      - "3000:3000"